ALTER TABLE `users`
  MODIFY `role` ENUM('ADMIN', 'USER', 'READER', 'AUTHOR') NOT NULL DEFAULT 'USER';

UPDATE `users`
SET `role` = 'READER'
WHERE `role` = 'USER';

ALTER TABLE `users`
  MODIFY `role` ENUM('ADMIN', 'READER', 'AUTHOR') NOT NULL DEFAULT 'READER';
